<?php

use Illuminate\Database\Seeder;

class CityTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        	DB::table('cities')->insert(["id" => 360542, "name" => "Al Qurayn"]); 
            DB::table('cities')->insert(["id" => 361495, "name" => "Al Ayyat"]); 
            DB::table('cities')->insert(["id" => 362882, "name" => "Abu al Matamir"]); 
            DB::table('cities')->insert(["id" => 350789, "name" => "Qalyub"]); 
            DB::table('cities')->insert(["id" => 355795, "name" => "Halwan"]); 
            DB::table('cities')->insert(["id" => 356933, "name" => "Farshut"]); 
            DB::table('cities')->insert(["id" => 356945, "name" => "Faraskur"]); 
            DB::table('cities')->insert(["id" => 356989, "name" => "Faqus"]); 
            DB::table('cities')->insert(["id" => 358095, "name" => "Diyarb Najm"]); 
            DB::table('cities')->insert(["id" => 358108, "name" => "Disuq"]); 
            DB::table('cities')->insert(["id" => 358115, "name" => "Dishna"]); 
            DB::table('cities')->insert(["id" => 358172, "name" => "Dikirnis"]); 
            DB::table('cities')->insert(["id" => 358269, "name" => "Dayrut"]); 
            DB::table('cities')->insert(["id" => 358274, "name" => "Dayr Mawas"]); 
            DB::table('cities')->insert(["id" => 358970, "name" => "Basyun"]); 
            DB::table('cities')->insert(["id" => 359173, "name" => "Bani Suwayf"]); 
            DB::table('cities')->insert(["id" => 359280, "name" => "Banha"]); 
            DB::table('cities')->insert(["id" => 359576, "name" => "Awsim"]); 
            DB::table('cities')->insert(["id" => 359710, "name" => "At Tall al Kabir"]); 
            DB::table('cities')->insert(["id" => 359797, "name" => "Muḩāfaz̧at as Suways"]); 
            DB::table('cities')->insert(["id" => 360048, "name" => "Ashmun"]); 
            DB::table('cities')->insert(["id" => 360464, "name" => "Al Wasitah"]); 
            DB::table('cities')->insert(["id" => 7603259, "name" => "Muḩāfaz̧at al Uqşur"]); 
            DB::table('cities')->insert(["id" => 360531, "name" => "Al Qusayr"]); 
            DB::table('cities')->insert(["id" => 360612, "name" => "Al Qanayat"]); 
            DB::table('cities')->insert(["id" => 360615, "name" => "Al Qanatir al Khayriyah"]); 
            DB::table('cities')->insert(["id" => 360754, "name" => "Al Manzilah"]); 
            DB::table('cities')->insert(["id" => 360928, "name" => "Al Khankah"]); 
            DB::table('cities')->insert(["id" => 360995, "name" => "Al Jizah"]); 
            DB::table('cities')->insert(["id" => 361103, "name" => "Al Ibrahimiyah"]); 
            DB::table('cities')->insert(["id" => 361179, "name" => "Al Hawamidiyah"]); 
            DB::table('cities')->insert(["id" => 361329, "name" => "Al Fashn"]); 
            DB::table('cities')->insert(["id" => 361394, "name" => "Al Bawiti"]); 
            DB::table('cities')->insert(["id" => 361435, "name" => "Al Balyana"]); 
            DB::table('cities')->insert(["id" => 361457, "name" => "Al Bajur"]); 
            DB::table('cities')->insert(["id" => 361478, "name" => "Al Badari"]); 
            DB::table('cities')->insert(["id" => 361546, "name" => "Al Arish"]); 
            DB::table('cities')->insert(["id" => 361661, "name" => "Akhmim"]); 
            DB::table('cities')->insert(["id" => 361702, "name" => "Aja"]); 
            DB::table('cities')->insert(["id" => 361827, "name" => "Ad Dilinjat"]); 
            DB::table('cities')->insert(["id" => 362277, "name" => "Abu Qurqas"]); 
            DB::table('cities')->insert(["id" => 362485, "name" => "Abu Kabir"]); 
            DB::table('cities')->insert(["id" => 362973, "name" => "Abnub"]); 
            DB::table('cities')->insert(["id" => 419435, "name" => "Az Zarqa"]); 
            DB::table('cities')->insert(["id" => 7521348, "name" => "Ain Sukhna"]); 
            DB::table('cities')->insert(["id" => 359678, "name" => "Tor"]); 
            DB::table('cities')->insert(["id" => 7910966, "name" => "Beheira"]); 
            DB::table('cities')->insert(["id" => 346030, "name" => "Zifta"]); 
            DB::table('cities')->insert(["id" => 347236, "name" => "Toukh"]); 
            DB::table('cities')->insert(["id" => 347542, "name" => "Tamiyah"]); 
            DB::table('cities')->insert(["id" => 347634, "name" => "Tahta"]); 
            DB::table('cities')->insert(["id" => 347749, "name" => "Sumusta as Sultani"]); 
            DB::table('cities')->insert(["id" => 348112, "name" => "Sidi Salim"]); 
            DB::table('cities')->insert(["id" => 349114, "name" => "Shirbin"]); 
            DB::table('cities')->insert(["id" => 349156, "name" => "Shibin al Qanatir"]); 
            DB::table('cities')->insert(["id" => 349715, "name" => "Samannud"]); 
            DB::table('cities')->insert(["id" => 349717, "name" => "Samalut"]); 
            DB::table('cities')->insert(["id" => 350370, "name" => "Quwaysina"]); 
            DB::table('cities')->insert(["id" => 350376, "name" => "Qutur"]); 
            DB::table('cities')->insert(["id" => 350422, "name" => "Kousa"]); 
            DB::table('cities')->insert(["id" => 352344, "name" => "Minyat an Nasr"]); 
            DB::table('cities')->insert(["id" => 352354, "name" => "Minuf"]); 
            DB::table('cities')->insert(["id" => 352628, "name" => "Matay"]); 
            DB::table('cities')->insert(["id" => 352679, "name" => "Mashtul as Suq"]); 
            DB::table('cities')->insert(["id" => 352913, "name" => "Manfalut"]); 
            DB::table('cities')->insert(["id" => 353219, "name" => "Madinat Sittah Uktubar"]); 
            DB::table('cities')->insert(["id" => 353828, "name" => "Kawm Hamadah"]); 
            DB::table('cities')->insert(["id" => 354105, "name" => "Kafr Saqr"]); 
            DB::table('cities')->insert(["id" => 354502, "name" => "Kafr ash Shaykh"]); 
            DB::table('cities')->insert(["id" => 354775, "name" => "Kafr ad Dawwar"]); 
            DB::table('cities')->insert(["id" => 354981, "name" => "Juhaynah"]); 
            DB::table('cities')->insert(["id" => 355392, "name" => "Izbat al Burj"]); 
            DB::table('cities')->insert(["id" => 355420, "name" => "Itsa"]); 
            DB::table('cities')->insert(["id" => 355648, "name" => "Ibshaway"]); 
            DB::table('cities')->insert(["id" => 355939, "name" => "Hihya"]); 
            DB::table('cities')->insert(["id" => 356000, "name" => "Hawsh Isa"]); 
            DB::table('cities')->insert(["id" => 356806, "name" => "Fuwah"]); 
            DB::table('cities')->insert(["id" => 358600, "name" => "Bush"]); 
            DB::table('cities')->insert(["id" => 358821, "name" => "Bilqas Qism Awwal"]); 
            DB::table('cities')->insert(["id" => 359953, "name" => "Ash Shuhada"]); 
            DB::table('cities')->insert(["id" => 360526, "name" => "Al Qusiyah"]); 
            DB::table('cities')->insert(["id" => 360686, "name" => "Al Minya"]); 
            DB::table('cities')->insert(["id" => 360716, "name" => "Al Matariyah"]); 
            DB::table('cities')->insert(["id" => 360773, "name" => "Al Manshah"]); 
            DB::table('cities')->insert(["id" => 361029, "name" => "Al Jamaliyah"]); 
            DB::table('cities')->insert(["id" => 361213, "name" => "Al Hamul"]); 
            DB::table('cities')->insert(["id" => 6692512, "name" => "El Gouna"]); 
            DB::table('cities')->insert(["id" => 6692518, "name" => "Makadi Bay"]); 
            DB::table('cities')->insert(["id" => 357994, "name" => "Arab Republic of Egypt"]); 
            DB::table('cities')->insert(["id" => 360688, "name" => "Muḩāfaz̧at al Minyā"]); 
            DB::table('cities')->insert(["id" => 432887, "name" => "Al Amal (Nimrah Thamāniyah)"]); 
            DB::table('cities')->insert(["id" => 361323, "name" => "Muḩāfaz̧at al Fayyūm"]); 
            DB::table('cities')->insert(["id" => 359416, "name" => "Bāhā"]); 
            DB::table('cities')->insert(["id" => 361056, "name" => "Muḩāfaz̧at al Ismā‘īlīyah"]); 
            DB::table('cities')->insert(["id" => 349598, "name" => "Sarābiyūm"]); 
            DB::table('cities')->insert(["id" => 361370, "name" => "Muḩāfaz̧at al Buḩayrah"]); 
            DB::table('cities')->insert(["id" => 408911, "name" => "Al Wiḩdah"]); 
            DB::table('cities')->insert(["id" => 357678, "name" => "‘Izbat Abū ‘Aţwah"]); 
            DB::table('cities')->insert(["id" => 358448, "name" => "Damanhur"]); 
            DB::table('cities')->insert(["id" => 355182, "name" => "Muḩāfaz̧at Janūb Sīnā’"]); 
            DB::table('cities')->insert(["id" => 349340, "name" => "Sharm ash Shaykh"]); 
            DB::table('cities')->insert(["id" => 360631, "name" => "Muḩāfaz̧at al Qāhirah"]); 
            DB::table('cities')->insert(["id" => 7922173, "name" => "Al ‘Atabah"]); 
            DB::table('cities')->insert(["id" => 361059, "name" => "Muḩāfaz̧at al Iskandarīyah"]); 
            DB::table('cities')->insert(["id" => 361058, "name" => "Alexandria"]); 
            DB::table('cities')->insert(["id" => 360015, "name" => "Ash Shāţibī"]); 
            DB::table('cities')->insert(["id" => 361320, "name" => "Al Fayyum"]); 
            DB::table('cities')->insert(["id" => 361294, "name" => "Muḩāfaz̧at al Gharbīyah"]); 
            DB::table('cities')->insert(["id" => 347497, "name" => "Tanda"]); 
            DB::table('cities')->insert(["id" => 361468, "name" => "Muḩāfaz̧at al Baḩr al Aḩmar"]); 
            DB::table('cities')->insert(["id" => 6692521, "name" => "Port el Ghalib"]); 
            DB::table('cities')->insert(["id" => 354365, "name" => "Kafr az Zayyat"]); 
            DB::table('cities')->insert(["id" => 360016, "name" => "Muḩāfaz̧at ash Sharqīyah"]); 
            DB::table('cities')->insert(["id" => 359493, "name" => "Az Zaqaziq"]); 
            DB::table('cities')->insert(["id" => 360621, "name" => "Muḩāfaz̧at al Qalyūbīyah"]); 
            DB::table('cities')->insert(["id" => 351022, "name" => "Nişf Atrīb"]); 
            DB::table('cities')->insert(["id" => 350546, "name" => "Muḩāfaz̧at Qinā"]); 
            DB::table('cities')->insert(["id" => 350550, "name" => "Qina"]); 
            DB::table('cities')->insert(["id" => 357542, "name" => "‘Ezbet el-Auqât"]); 
            DB::table('cities')->insert(["id" => 359781, "name" => "Muḩāfaz̧at Asyūţ"]); 
            DB::table('cities')->insert(["id" => 359783, "name" => "Asyut"]); 
            DB::table('cities')->insert(["id" => 347794, "name" => "Muḩāfaz̧at Sūhāj"]); 
            DB::table('cities')->insert(["id" => 347796, "name" => "Suhaj"]); 
            DB::table('cities')->insert(["id" => 358044, "name" => "Muḩāfaz̧at Dumyāţ"]); 
            DB::table('cities')->insert(["id" => 358048, "name" => "Damietta"]); 
            DB::table('cities')->insert(["id" => 359787, "name" => "Muḩāfaz̧at Aswān"]); 
            DB::table('cities')->insert(["id" => 359792, "name" => "Aswan"]); 
            DB::table('cities')->insert(["id" => 358617, "name" => "Muḩāfaz̧at Būr Sa‘īd"]); 
            DB::table('cities')->insert(["id" => 412814, "name" => "Syria"]); 
            DB::table('cities')->insert(["id" => 351483, "name" => "Naj‘ al Khuţbah"]); 
            DB::table('cities')->insert(["id" => 361849, "name" => "Muḩāfaz̧at ad Daqahlīyah"]); 
            DB::table('cities')->insert(["id" => 347591, "name" => "Talkha"]); 
            DB::table('cities')->insert(["id" => 349852, "name" => "Sāḩil Ţahţā"]); 
            DB::table('cities')->insert(["id" => 359212, "name" => "Bani Mazar"]); 
            DB::table('cities')->insert(["id" => 359171, "name" => "Muḩāfaz̧at Banī Suwayf"]); 
            DB::table('cities')->insert(["id" => 361024, "name" => "Al Janādilah"]); 
            DB::table('cities')->insert(["id" => 360829, "name" => "Al Mahallah al Kubra"]); 
            DB::table('cities')->insert(["id" => 360689, "name" => "Muḩāfaz̧at al Minūfīyah"]); 
            DB::table('cities')->insert(["id" => 347612, "name" => "Tala"]); 
            DB::table('cities')->insert(["id" => 353223, "name" => "Madīnat as Sādāt"]); 
            DB::table('cities')->insert(["id" => 362004, "name" => "Abu Tij"]); 
            DB::table('cities')->insert(["id" => 7916170, "name" => "Masākin al Akhshāb wa ash Shāy"]); 
            DB::table('cities')->insert(["id" => 354076, "name" => "Kafr Shukr"]); 
            DB::table('cities')->insert(["id" => 358620, "name" => "Bur Safajah"]); 
            DB::table('cities')->insert(["id" => 349158, "name" => "Shibin al Kawm"]); 
            DB::table('cities')->insert(["id" => 352951, "name" => "Mallawi"]); 
            DB::table('cities')->insert(["id" => 360761, "name" => "Al Mansurah"]); 
            DB::table('cities')->insert(["id" => 362610, "name" => "Abū Ḩammād al Maḩaţţah"]); 
            DB::table('cities')->insert(["id" => 355628, "name" => "Idku"]); 
            DB::table('cities')->insert(["id" => 350203, "name" => "Rosetta"]); 
            DB::table('cities')->insert(["id" => 351434, "name" => "Naj Hammadi"]); 
            DB::table('cities')->insert(["id" => 355026, "name" => "Jirja"]); 
            DB::table('cities')->insert(["id" => 360997, "name" => "Muḩāfaz̧at al Jīzah"]); 
            DB::table('cities')->insert(["id" => 359900, "name" => "As Saff"]); 
            DB::table('cities')->insert(["id" => 358840, "name" => "Bilbays"]); 
            DB::table('cities')->insert(["id" => 346315, "name" => "Wāsiţ"]); 
            DB::table('cities')->insert(["id" => 353802, "name" => "Kawm Umbu"]); 
            DB::table('cities')->insert(["id" => 355015, "name" => "Jizayy"]); 
            DB::table('cities')->insert(["id" => 354500, "name" => "Muḩāfaz̧at Kafr ash Shaykh"]); 
            DB::table('cities')->insert(["id" => 359304, "name" => "Balṭîm"]); 
            DB::table('cities')->insert(["id" => 411165, "name" => "Idfu"]); 
            DB::table('cities')->insert(["id" => 352603, "name" => "Muḩāfaz̧at Maţrūḩ"]); 
            DB::table('cities')->insert(["id" => 352733, "name" => "Marsa Matruh"]); 
            DB::table('cities')->insert(["id" => 7522531, "name" => "testing"]); 
            DB::table('cities')->insert(["id" => 359927, "name" => "Aşlān"]); 
            DB::table('cities')->insert(["id" => 355005, "name" => "Al Jubayl"]); 
            DB::table('cities')->insert(["id" => 351388, "name" => "Naj‘ Tinjār"]); 
            DB::table('cities')->insert(["id" => 7280514, "name" => "Naama"]); 
            DB::table('cities')->insert(["id" => 414338, "name" => "‘Uqrat Şafḩah"]); 
            DB::table('cities')->insert(["id" => 410366, "name" => "Al Manākh"]); 
            DB::table('cities')->insert(["id" => 361133, "name" => "Al Ḩubayl"]); 
            DB::table('cities')->insert(["id" => 361291, "name" => "Al Ghardaqah"]); 
            DB::table('cities')->insert(["id" => 362041, "name" => "Abu Sunbul"]); 
            DB::table('cities')->insert(["id" => 358333, "name" => "Dawwār Abū al ‘Āşī"]); 
            DB::table('cities')->insert(["id" => 415505, "name" => "‘Izbat Nādī aş Şayd"]); 
            DB::table('cities')->insert(["id" => 359256, "name" => "Banī Ghālib"]); 
            DB::table('cities')->insert(["id" => 349401, "name" => "Muḩāfaz̧at Shamāl Sīnā’"]); 
            DB::table('cities')->insert(["id" => 357790, "name" => "El-Qushlâqât"]); 
            DB::table('cities')->insert(["id" => 355449, "name" => "Isna"]); 
            DB::table('cities')->insert(["id" => 358619, "name" => "Port Said"]); 
            DB::table('cities')->insert(["id" => 359796, "name" => "Suez"]); 
            DB::table('cities')->insert(["id" => 360502, "name" => "Luxor"]); 
            DB::table('cities')->insert(["id" => 360630, "name" => "Cairo"]); 
            DB::table('cities')->insert(["id" => 361055, "name" => "Ismailia"]); 
            DB::table('cities')->insert(["id" => 347863, "name" => "Siwah"]); 
            DB::table('cities')->insert(["id" => 360483, "name" => "Muḩāfaz̧at al Wādī al Jadīd"]); 
            DB::table('cities')->insert(["id" => 350661, "name" => "Qasr al Farafirah"]); 
            DB::table('cities')->insert(["id" => 350893, "name" => "Nuwaybia"]); 
            DB::table('cities')->insert(["id" => 352736, "name" => "Marsa Alam"]); 
            DB::table('cities')->insert(["id" => 358245, "name" => "Dhahab"]); 
            DB::table('cities')->insert(["id" => 360923, "name" => "Al Kharijah"]); 
            DB::table('cities')->insert(["id" => 361612, "name" => "Al Alamayn"]);
    }
}
